app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::controller('login', 'loginController');

//Route::group(array('before' => 'auth'), function()
//{

	Route::resource('users', 'userController');
	Route::get('/',function(){return View::make('index');});

	Route::get('pago/venta/{idVenta}', ['as' => 'pagar', 'uses' => function($idVenta)
	{
		$pago = pago::where('idVenta', '=', $idVenta)->get()->first(); // Validar si aún no hay hecho un pago para esta venta.
		if(is_null($pago) ){
			//return "no existe este baboso";
			$pago = new pago();
			$pago->prima = 0;
			$form_data = array('route' => 'pago.store', 'method' => 'POST');
			$pago->idVenta = $idVenta;
			//$
	        $action    = 'Continuar';
			return View::make('pagos.nuevo', compact('pago','form_data', 'action'));
		}
			//route('pago.edit', $pago->id)
		//return $pago;
		return Redirect::route('pago.edit', $pago->id);
	}]);

	//Rutas para las categorias
	require (__DIR__ . '/routes/categorias.php');

	//Rutas para las clientes
	require (__DIR__ . '/routes/clientes.php'); 

	//Rutas para las compras
	require (__DIR__ . '/routes/compras.php');





	Route::post('buscar', function()
	{
		$option = Input::get('opciones');
		$term = Input::get('term');

		//$term = 'hola mi amor';

		if($option == 'cliente')
			return Redirect::route('buscarCliente', $term);
		elseif($option == 'proveedor')
			return Redirect::route('buscarProveedor', $term);
		elseif($option == 'producto')
			return Redirect::route('buscarProducto', $term);
		elseif($option == 'categoria')
			return Redirect::route('buscarCategoria', $term);
		elseif($option == 'pagos')
			return Redirect::route('buscarPago', $term);
		elseif($option == 'inventario')
			return Redirect::route('buscarInventario', $term);

		return $option;
		//Redirect::route('clientes');
	//	return "C";
	});

	Route::controller('api','apiController');
	Route::controller('consultas','consultas');

 
//Rutas para las busquedas
	Route::get('proveedores/buscar/{term}', ['as' => 'buscarProveedor', 'uses' => 'proveedoresController@buscar']);
	Route::get('productos/buscar/{term}',   ['as' => 'buscarProducto',  'uses' => 'ProductoController@buscar']);
 	Route::get('categorias/buscar/{term}',  ['as' => 'buscarCategoria', 'uses' => 'categoryController@buscar']);
 	Route::get('pagos/buscar/{term}',       ['as' => 'buscarPago',      'uses' => 'pagoController@buscar']);
 	Route::get('inventario/buscar/{term}',       ['as' => 'buscarInventario',      'uses' => 'inventarioController@buscar']);
 
	//Route::resource('categorias','CategoriaController');
	//Route::resource('clientes','clienteController');
	//Route::resource('compras','comprasController');

 	Route::get('proveedores/compras/{id}', ['as' => 'comprasProveedor', 'uses' => 'proveedoresController@compras']);
 	Route::get('proveedores/productos/{id}', ['as' => 'productosProveedor', 'uses' => 'proveedoresController@productos']);


	Route::resource('detallecompra','detalleCompraController');
	Route::resource('detalleenvio','detalleEnvioController');
	Route::resource('detallepago','detallePagoController');
	Route::resource('detalleventa','detalleVentaController');
	Route::resource('envio','ordenEnvioController');
	Route::resource('fiadores','FiadoresController');
	Route::resource('inventario','InventarioController');
	Route::resource('vendedores','VendedoresController');
	Route::resource('pago', 'pagoController');
	Route::get('pagos/mora', ['as' => 'enMora', 'uses' => 'pagoController@mora']);
	Route::get('pagos/realizados', ['as' => 'pagosRealizados', 'uses' => 'pagoController@pagosRealizados']);

	Route::resource('productos','ProductoController');
	Route::resource('proveedores','ProveedoresController');
	Route::resource('sucursales','sucursalesController');
	Route::resource('ventas','ventaController');

	Route::get('kardex', ['as' => 'kardex', 'uses' => 'ProductoController@kardex']);


	//Inventario
	Route::get('inventario', ['as' => 'inventario', 'uses' => 'inventarioController@index']);
	Route::get('entradas-salidas', ['as' => 'entradaSalida', 'uses' => 'inventarioController@entradaSalida']);
	Route::post('entradas-salidas', ['as' => 'entradaSalidaProducto', 'uses' => 'inventarioController@entradaSalidaProducto']);


	//mostrar detalles de compras
	Route::get('venta/{id}', ['as' => 'productoCliente', 'uses' => 'ventasController@cliente']);
	Route::get('venta/productos/{tabla}/{id}', ['as' => 'producto', 'uses' => 'ventasController@productos']);

//});

app/models/detalleCompra.php
<?php

class detalleCompra extends Eloquent
{
	protected $guarded = array();
	public $errors;

	protected $table = "detalleCompras";


    protected $fillable = array('compra_id', 'idProducto', 'precioSinIva', 'precioConIva', 'cantidad', 'detalle');


    public function compra()
    {
    	return $this->belongsTd('compra');
    }


    public function isValid($data)
    {
        $rules = array(
            'compra_id'     => 'required',
            'idProducto'     => 'required',
            'precioSinIva'     => 'required',
            'cantidad'     => 'required',
        );
        
        $validator = Validator::make($data, $rules);
        
        if ($validator->passes())
        {
            return true;
        }
        
        $this->errors = $validator->errors();
        
        return false;
    }


    public function ValidAndSave($data)
    {
        if($this->isValid($data))
        {
            //$this->// Si la data es valida se la asignamos al usuario
            $this->fill($data);
            // Guardamos el usuario
            $this->save();
            return true;
        }
        else 
            return false;
    }

    public function getTotalAttribute()
    {
        return ($this->precioSinIva * $this->cantidad);
    }
    public function producto()
    {
        return $this->belongsTo('producto', 'idProducto');
    }


}

app/models/detalleVenta.php
<?php

class detalleVenta extends Eloquent
{
	protected $guarded = array();
	public $errors;

	protected $table = "detalleVentas";


    protected $fillable = array('idVenta', 'idProducto', 'precio', 'cantidad', 'detalle');

    public function isValid($data)
    {
        $rules = array(
            'idVenta'     => 'required',
            'idProducto'  => 'required',
            'precio'      => 'required',
            'cantidad'    => 'required',
        );
        
        $validator = Validator::make($data, $rules);
        
        if ($validator->passes())
        {
            return true;
        }
        
        $this->errors = $validator->errors();
        
        return false;
    }


    public function ValidAndSave($data)
    { 
        if($this->isValid($data))
        {
            //$this->// Si la data es valida se la asignamos al usuario
            $this->fill($data);
            // Guardamos el usuario
            $this->save();
            return true;
        }
        else 
            return false;
    }

    public function productos()
    {
        return $this->belongsTo('producto', 'idProducto');
    }

    public function venta()
    {
        return $this->belongsTo('venta', 'idVenta');
    }

}

app/controllers/detalleVentaController.php
 <?php

class detalleVentaController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		Redirect::to('/');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		Redirect::to('/');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
		Redirect::to('/');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		//
		$venta = venta::find($id);
		if (is_null ($venta))
        {
            App::abort(404);
        }
		$form_data = array('route' => array('detalleventa.update', $venta->id), 'method' => 'PATCH');
        $action    = 'Continuar';
		//var_dump( $cliente);
		return View::make('detalleventas/nuevo', compact('venta', 'form_data', 'action'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
		//
		//

		$detalleVenta = new detalleVenta();
        // Obtenemos la data enviada por el usuario
        $data = Input::all();
        
        // Revisamos si la data es válido
        if ($detalleVenta->ValidAndSave($data))
        {   
        	$venta = venta::find($id);
        	return Redirect::route('detalleventa.edit', $venta->id);
        	//return 'Detalle almacenado correctamente';
        }
        else
        {return Redirect::route('detalleventa.edit', $id)->withInput()->withErrors($detalleVenta->errors);}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
		//
		$detalleVenta = detalleVenta::find($id);
        
        if (is_null ($detalleVenta))
        {
            App::abort(404);
        }
        
        $detalleVenta->delete();

        if (Request::ajax())
        {
            return Response::json(array (
                'success' => true,
                'msg'     => 'Detalle  ' . $detalleVenta->id  .' eliminado',
                'id'      => $detalleVenta->id
            ));
        }
        else
        {
            return Redirect::route('detalleventas');
        }
	}

}

app/views/detalleVentas/detail.blade.php
@extends ('index')


@section ('title') Detalle de la Compra {{$compra->id}} @stop

@section ('content')

<div class="panel panel-default">
<div class="panel-heading">
    <h1>{{$compra->comprobante}} </h1>
        {{ HTML::link('compras', 'Todos', array('class' => 'glyphicon glyphicon-list'))}}
        
       {{ HTML::link('compras/create', 'Nuevo', array('class' => 'glyphicon glyphicon-file'))}}
  </div>
  <div class="panel-body">


  <div class="row">
  	
	  <div class="col-md-3"> 
	  		
	  </div>


  </div>




</div>  
@stop

app/views/detalleVentas/list.blade.php
@extends ('index')

@section ('title') Lista de ventas @stop

@section ('content')

<div class="panel panel-default">
  <div class="panel-heading">
    <p>
        <h1>Lista de ventas </h1>
        {{ HTML::link('ventas/create', 'Nuevo', array('class' => 'glyphicon glyphicon-file'))}}
    </p>
  </div>
  <div class="panel-body">
 
    {{ $ventas->links()}} 

  <table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
        <th>Codigo</th>
        <th>Proveedor</th>
        <th>Comprobante</th>
        <th>Fecha</th>
        <th>Creado</th>
        <th>Modificado</th>
        <th>Opciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($ventas as $venta)
    <tr>
        <td>{{ $venta->id }}</td>
        <td>{{ $venta->idProveedor }}</td>
        <td>{{ $venta->comprobante }}</td>
        <td>{{ date_format($venta->fecha, 'd/m/Y'}}</td>
        <td>{{ $venta->created_at}}</td>
        <td>{{ $venta->updated_at}}</td>
        <td>
            <a href="{{ route('ventas.edit', $venta->id) }}" class="btn btn-primary glyphicon glyphicon-edit"> </a>
            <a href="{{ route('ventas.show', $venta->id) }}" class="btn btn-primary glyphicon glyphicon-search"> </a>
             
            <a href="#" data-id="{{ $venta->id }}" class="btn btn-danger btn-delete glyphicon glyphicon-remove"> </a>


        </td>
    </tr>

    @endforeach
    </tbody>
  </table>
</div>
</div>

{{--usado para eliminar usuario --}}
{{ Form::open(array('route' => array('ventas.destroy', 'CLIENTE_ID'), 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete')) }}
{{ Form::close() }}
@stop

app/views/detalleVentas/nuevo.blade.php
@extends ('index')


@section ('title') Detalle de venta @stop

@section ('content')

<div class="panel panel-default">
<div class="panel-heading">
    <h1> Detalle de venta</h1>
        {{ HTML::link('ventas', 'Todos', array('class' => 'glyphicon glyphicon-list'))}}
        
       {{ HTML::link('ventas/create', 'Nuevo', array('class' => 'glyphicon glyphicon-file'))}}
  </div>
  <div class="panel-body">



<div class="list-group">
    <a href="{{ route('ventas.edit', $venta->id) }}" class="list-group-item" >
      <h4 class="list-group-item-heading">{{ $venta->cliente->nombre}} </h4>
      <p class="list-group-item-text"> {{ $venta->cliente->direccion}} <small> {{ $venta->cliente->telefono}}</small></p>
    </a>
</div>




  @include ('errors', array('errors' => $errors))

{{ Form::model($venta, $form_data, array('role' => 'form')) }}
    
        {{ Form::hidden('idVenta', $venta->id, array('class' => 'form-control', 'readOnly', 'placeholder' => 'ID Producto')) }}        
      
  <div class="row">
      <div class="form-group col-md-1">
        {{ Form::label('idProducto', 'ID.') }}
        {{ Form::text('idProducto', null, array('class' => 'form-control', 'readOnly', 'placeholder' => 'ID Producto')) }}        
      </div>
      <div class="form-group col-md-2">
        {{ Form::label('search', 'Producto')}}
        {{ Form::text('search', null, array( 'class' => 'form-control', 'placeholder' => 'Nombre de producto', 'data-url' => 'producto', 'data-cod' => 'idProducto')) }}
      </div>
      <div class="form-group col-md-2">
        {{ Form::label('precio', 'Precio') }}
        <div class="input-group">
          <span class="input-group-addon">$</span>
          {{ Form::text('precio', null, array('placeholder' => 'Precio', 'class' => 'form-control')) }}        
        </div>
      </div>
      <div class="form-group col-md-1">
        {{ Form::label('cantidad', 'Cantidad') }}
        {{ Form::text('cantidad', null, array('class' => 'form-control')) }}        
      </div>
      <div class="form-group col-md-2">
        {{ Form::label('detalle', 'Detalles') }}
        {{ Form::text('detalle', null, array('class' => 'form-control')) }}        
      </div>
    </div>
@if($venta->Pago == 'Credito')
  {{
    HTML::link('pago/venta/' . $venta->id, 'Agregar Pagos', array('class' => 'btn btn-danger')) 
  }}
  @endif

    {{ Form::button($action, array('type' => 'submit', 'class' => 'btn btn-success')) }}
  {{Form::close()}}

  
  </div>


<table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
        <th>Cantidad</th>
        <th>Producto</th>
        <th>Detalles</th>
        <th>Precio</th>
        <th>Total</th>
        <th>Opciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($venta->detalle as $detalle)
    <tr>
        <td>{{ $detalle->cantidad }}</td>
        <td>{{ $detalle->productos->nombre }}</td>
        <td>{{ $detalle->detalle }}</td>
        <td>$ {{ $detalle->precio }}</td>
        <td>$ {{$detalle->precio * $detalle->cantidad}}</td>
        <td>
             
            <a href="#" data-id="{{ $detalle->id }}" class="btn btn-danger btn-delete glyphicon glyphicon-remove"> </a>


        </td>
    </tr>

    @endforeach<tr>
        <td></td>
        <td></td>
        <td></td>
        <td>Total</td>
        <td>
            $ {{ $venta->total(); }}
        </td>
        <td></td>
    </tr>
    </tbody>
  </table>



</div>  
{{--usado para eliminar usuario --}}
{{ Form::open(array('route' => array('detalleventa.destroy', 'CLIENTE_ID'), 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete')) }}
{{ Form::close() }}
@stop